pipeline {
	agent {
		docker {
			image 'maven:3-ubuntu'
			args '-v /root/.m2:/root/.m2'
		}
	}
	tools {nodejs "node"}
	stages {
		stage('Build') {
			steps {
				echo "Building"
				sh 'cd spoiled-tomatillos && mvn clean install'
			}
		}
		stage('Test'){
			steps {
				echo "Testing"
				sh 'mvn -f spoiled-tomatillos/pom.xml test'
			}
		}
    	stage('SonarQube') {
      		steps {
        		withSonarQubeEnv('SonarQube') {
          			sh 'mvn -f spoiled-tomatillos/pom.xml clean install'
          			sh 'mvn -f spoiled-tomatillos/pom.xml sonar:sonar'
        		}
      		}
    	}
    /* Problems with configuration where it is failing but is linked to someone
         else's project on sonarqube.
    stage('Quality') {
      steps {
        sh 'sleep 30'
        timeout(time: 10, unit: 'MINUTES') {
          retry(5) {
            script {
              def qg = waitForQualityGate()
              if (qg.status != 'OK') {
                error "Pipeline aborted due to quality gate failure: ${qg.status}"
              }
            }
          }
        }
      }
    }
    */
	}
}
